### ISSUE TITLE
AWS instance not reading .cl files

### ISSUE THREAD

**Issue by yuchen-w** [HPCE/hpce-2014-cw4#16]
I am getting this error on the AWS instance.

```
Exception : LoadWorld : File does not start with HPCEHeatWorldV0.
```

I find it strange because it compiles and runs fine using Windows PowerShell (Compiled using VS) and Cygwin (re-compiled using cmake):
![image](https://cloud.githubusercontent.com/assets/3355737/6238573/2547a016-b6f4-11e4-9929-103ac58f96dc.png)

However, taking the same code and running it on AWS:
![image](https://cloud.githubusercontent.com/assets/3355737/6238700/44fff5a6-b6f5-11e4-886c-cc8112fcfff8.png)

Edit: After doing some digging, it would appear that the directory "src/your_login" is being found, but the various .cl files are not. Still not sure about how to fix it though.

**Comment by m8pple** [comment]
Some things to check are:
- Are the .cl files definitely over there, i.e. they've made it into git, and are present on the AWS machine?
- Given you've set up $(HPCE_CL_SRC_DIR), if you do `(cd $(HPCE_CL_SRC_DIR); ls */*/*.cl)`, does it echo back the .cl paths as they appear in the program?
- Are you using the correct direction slashes from within the host code (posix rather than windows?)
- Are the permissions on the .cl files correct, so they are readable?

If loading the .cl is not working, you might want to create a tiny test program which only
loads the .cl file, then try opening that in GDB and stepping over the part where it opens
the file.

**Comment by chungcyk** [comment]
I've got the same problem (coming from a windows environment) 

For the second test though, did you mean to do cd $(HPCE_CL_SRC_DIR)? because the ls works find at the root and does return the path (I'm thinking \* means wildcard)

**Comment by yuchen-w** [comment]
For the second test, I'm not getting anything when I do 

```
(cd $(HPCE_CL_SRC_DIR); ls */*/*.cl)
```

with my environment variable set as:
![image](https://cloud.githubusercontent.com/assets/3355737/6270654/3848f36c-b853-11e4-9d4e-50f9d39a0a70.png)

I do however get the following if I just run ls _/_/*.cl
![image](https://cloud.githubusercontent.com/assets/3355737/6270662/49f7089c-b853-11e4-8aeb-6cdbd2cbf106.png)

With regards to point 3, I've tried both of the following:

```
std::string baseDir = "src/yw4311";     
std::string baseDir = "./src/yw4311";       
```

Both return the same error.

With point 4, it would appear that I have read permissions:
![image](https://cloud.githubusercontent.com/assets/3355737/6270953/6c65fe86-b855-11e4-895f-52202e89ee75.png)

**Comment by yuchen-w** [comment]
I think I might be wrong about the program not being able to find the *.cl files. I'm getting a segmentation fault when I run my step_world functions which require a .cl file

**Comment by yuchen-w** [comment]
I've fixed it now. I copied the original LoadSource function back in and that's fixed it all. Silly me.
